<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuditApp.Emp.Service\AuditApp.Emp.Service.csproj" />
    <ProjectReference Include="..\AuditApp.Log.Service\AuditApp.Log.Service.csproj" />
  </ItemGroup>

</Project>
