<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuditApp.DataAccess\AuditApp.DataAccess.csproj" />
    <ProjectReference Include="..\AuditApp.Log.Service\AuditApp.Log.Service.csproj" />
  </ItemGroup>

</Project>
